services:
  vasedapi:
    image: chgv99/vasedb-gateway:latest
    container_name: vasedb-gateway
    env_file: .env
    ports:
      - "80:8080" #HTTP
      - "443:8443" #HTTPS
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  postgresql_data: