spring:
  cache:
    cache-names:
      - rate-limit-buckets
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: http://${VASEDB_API_PRIVATE_IP}:8080  # Private IP of EC2-1
          predicates:
            - Host=${VASEDB_API_DOMAIN}
            - Path=/api/**
          filters:
            - PreserveHostHeader
        - id: metabase-service
          uri: http://${METAVASE_PRIVATE_IP}:3000  # Private IP of EC2-2
          predicates:
            - Host=${METAVASE_DOMAIN}
          filters:
            - PreserveHostHeader
            - RewritePath=/(.*), /$1
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/.*
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "{ \"error\": \"Too Many Requests\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: ${VASEDB_API_PER_IP_CAP}
              time: ${VASEDB_API_PER_IP_TIME}
              unit: ${VASEDB_API_PER_IP_TIME_UNIT}