name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: docker image deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vasedb-gateway:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/vasedb-gateway:latest
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DB_HOST,DB_USER,DB_PASSWORD
          script: |
            mkdir -p /home/ubuntu/vasedb-gateway
            cd /home/ubuntu/vasedb-gateway
          
            echo "VASEDB_API_PRIVATE_IP=${{ secrets.VASED_API_PRIVATE_IP }}" > .env
            echo "VASEDB_API_DOMAIN=${{ secrets.VASEDB_API_DOMAIN }}" >> .env
            echo "METAVASE_PRIVATE_IP=${{ secrets.METAVASE_PRIVATE_IP }}" >> .env
            echo "METAVASE_DOMAIN=${{ secrets.METAVASE_DOMAIN }}" >> .env
            echo "VASEDB_API_LISTEN_PORT=${{ secrets.VASEDB_API_LISTEN_PORT }}" >> .env
            echo "VASEDB_API_KEY=${{ secrets.VASEDB_API_KEY }}" >> .env
            echo "VASEDB_CLIENT_URL=${{ secrets.VASEDB_CLIENT_URL }}" >> .env
            echo "VASEDB_API_PER_IP_CAP=${{ secrets.VASEDB_API_PER_IP_CAP }}" >> .env
            echo "VASEDB_API_PER_IP_TIME=${{ secrets.VASEDB_API_PER_IP_TIME }}" >> .env
            echo "VASEDB_API_PER_IP_TIME_UNIT=${{ secrets.VASEDB_API_PER_IP_TIME_UNIT }}" >> .env
            cat .env
            docker compose pull
            docker compose up -d
